#!/bin/zsh

if [ -z "$1" ]; then
  echo "Error: A file name must be set, e.g. on \"Dalat trip checknote\"."
  exit 1
fi

file_name=$(echo "$1" | tr ' ' '-')
formatted_file_name=$(date "+%Y-%m-%d")_${file_name}.md
cd "/Users/truongle/Library/Mobile Documents/iCloud~md~obsidian/Documents/MartVault" || exit
touch "inbox/${formatted_file_name}"
nvim "inbox/${formatted_file_name}"
